# Name of the LaTeX source file
TEXFILE = resume.tex

# Name of the resulting PDF file (automatically derived from the .tex name)
PDF = $(TEXFILE:.tex=.pdf)

# Detect OS for the "view" target
UNAME := $(shell uname)
ifeq ($(findstring MINGW,$(UNAME)),MINGW)
    # Windows (MSYS/MinGW shell)
    OPEN_CMD = start
else ifeq ($(UNAME), Linux)
    OPEN_CMD = xdg-open
else ifeq ($(UNAME), Darwin)
    OPEN_CMD = open
else
    # Fallback if we don't recognize the platform:
    OPEN_CMD = echo "No recognized viewer for this OS:"
endif

# Default target: compile the PDF
all: $(PDF)

# Rule to compile the PDF using pdflatex.
# Running pdflatex twice is common to resolve cross-references, TOC, etc.
$(PDF): $(TEXFILE)
	pdflatex $(TEXFILE)
	pdflatex $(TEXFILE)

# Target to open/view the compiled PDF
view: $(PDF)
	$(OPEN_CMD) "$(PDF)"

# Clean up auxiliary files generated by pdflatex
clean:
	rm -f *.aux *.log *.toc *.out *.lot *.lof

# Declare targets that are not actual files.
.PHONY: all clean view
